version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart:  always
    ports:
      - "11434:11434"
    networks:
      - app_network
    volumes:
      - ollama_models:/root/.ollama  # Persist models inside a volume
  


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8001:8000"  # ChromaDB default port
    volumes:
      - chromadb_data:/chroma
    networks:
      - app_network

  backend:
    build: ./backend  # Ensure this directory contains a valid Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - ollama
      - mongodb
      - chromadb
    ports:
      - 5000:5000
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
      DB_NAME: "doc_db"
      DOCUMENTS_COLLECTION: "documents"
      USERS_COLLECTION: "users"
      SESSIONS_COLLECTION: "sessions"
      CHROMADB_URL: "http://chromadb:8000"  # Backend connects to ChromaDB
      EMBEDDING_MODEL_URL: "http://ollama:11434" 
      EMBEDDING_MODEL_NAME: "nomic-embed-text"
      LLAMA_MODEL: "mistral"
    networks:
      - app_network

  frontend:
    build: ../../frontend/ENS491-SUdoc # Ensure this matches the frontend Dockerfile location
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  mongodb_data:
  ollama_models:
  chromadb_data:

networks:
  app_network:
    driver: bridge
