version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: llm1-mongodb
    restart: unless-stopped
    ports:
      - "5004:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - llm1-app-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: llm1-chromadb
    restart: unless-stopped
    ports:
      - "5001:8000"  # ChromaDB default port
    environment:
      - CHROMA_DB_DIR=/chroma
      - CHROMA_PERSISTENCE_DIR=/chroma
    volumes:
      - chromadb_data:/data #/chroma
    networks:
      - llm1-app-network

  backend:
    build: ./backend  # Ensure this directory contains a valid Dockerfile
    container_name: llm1-backend
    restart: unless-stopped
    depends_on:
      - mongodb
      - chromadb
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0  # Ensure Flask listens on all interfaces
      - MONGO_URI=mongodb://root:example@mongodb:27017/
      - DB_NAME=doc_db
      - DOCUMENTS_COLLECTION=documents
      - USERS_COLLECTION=users
      - SESSIONS_COLLECTION=sessions
      - CHROMADB_URL=http://chromadb:8000
      - LLM_MODEL_NAME=meta-llama/Llama-3.1-8B-Instruct
      - TOKENIZER_NAME=codellama/CodeLlama-7b-Python-hf
      - LLM_URI=http://10.3.0.96:8888/v1
      - EMBEDDING_MODEL_URL=http://10.3.0.96:8888/v1/ # we load the embedding model to the backend server but we used to load it to the llm server before. 
      - EMBEDDING_MODEL_NAME=nomic-embed-text
      - EMBEDDING_MODEL_NAME_V2=nomic-ai/nomic-embed-text-v2-moe
      - SECRET_KEY=your_secret_key  # Replace with a strong secret key

    networks:
      - llm1-app-network


  # frontend:
  #   build: ../frontend # Ensure this matches the frontend Dockerfile location
  #   container_name: llm1-frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5005:3000"
  #   networks:
  #     - llm1-app-network

  nginx:
      image: nginx:latest
      container_name: llm1-nginx
      restart: unless-stopped   
      ports:
        - "5002:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
        - ./build:/usr/share/nginx/html:ro  # Mount the React build folder 
      depends_on:

        - backend
      networks:
        - llm1-app-network

volumes:
  mongodb_data:
  ollama_models:
  chromadb_data:

networks:
  llm1-app-network:
    driver: bridge
