version: 

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./your-react-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
