
flowchart TB
    %% Client Layer
    User((End User)) -->|HTTP Browser<br>localhost:5002| FE

    subgraph "Client_Layer"
        FE[Web Browser]
    end

    %% Presentation Layer
    FE -->|HTTP/HTTPS| NG
    
    subgraph "Presentation_Layer"
        NG[Nginx Web Server<br>Port 80]
        
        subgraph "Static React Build Files"
            UI[React Frontend UI Components]
            UI --> DM[Document Management]
            UI --> CI[Chat Interface]
        end
    end
    

    subgraph "Backend_Layer"
        %% Application Layer
        NG <-->|API Requests| API
        

        %% Data Layer
        subgraph "Data Layer"
            CDB[(ChromaDB<br>Port 8001)]
            MDB[(MongoDB<br>Port 27017)]
  
        end

        subgraph "Application_Layer"
            API[Flask REST API<br>Port 5001]
           
            API --> DocProc[Document<br>Processing and Management]
           
            API --> RAGP[RAG pipeline:
                query processing, history, retrieval, prompting] 

            API --> Auth[User Management: Authentication<br>& Authorization]
            API --> SessionMan[User Chat Session Management ]
            
        end
        

        %% LLM Services Layer
        subgraph "LLM Services Layer"
            VLLM[VLLM Service]
            VLLM --> GenText[Response Generation]
            VLLM --> GenEmb[Embedding Generation 
                - we used to have this in OLLAMA as LLM service but now it is in application layer]
        end
        


        
        %% Connections between layers
        DocProc -->|Document Storage| MDB 
        Auth -->|User Management| MDB
        SessionMan -->|Session Management| MDB
        RAGP --> |Relevant chunk search| CDB
        DocProc -->|Vector Store Operations,
            Chunk embedding storage | CDB
        RAGP -->|LLM based Requests| VLLM
       

    
    end
    
    %% Styling
    classDef client fill:#f9f9f9,stroke:#333,stroke-width:1px
    classDef presentation fill:#e3f2fd,stroke:#1565c0,stroke-width:1px
    classDef application fill:#e8f5e9,stroke:#2e7d32,stroke-width:1px
    classDef services fill:#f3e5f5,stroke:#7b1fa2,stroke-width:1px
    classDef data fill:#e8eaf6,stroke:#3f51b5,stroke-width:1px
    classDef user fill:#ffebee,stroke:#c62828,stroke-width:2px
    classDef interface fill:#e1f5fe,stroke:#01579b,stroke-width:1px
    classDef outer fill:#ffffff,stroke:#01579b,stroke-width:1px

    class FE client
    class User user
    class NG,UI,PDF,DM,CI presentation
    class API,Auth,DocProc,VSO,RAGP,SessionMan application
    class VLLM,GenText,GenEmb services
    class MDB,CDB data
    class Backend_Layer,Presentation_Layer,Client_Layer outer
